apiVersion: v1
kind: ConfigMap
metadata:
  name: ems-config
  namespace: ems-prod
data:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATA_REDIS_HOST: "redis-server"
  SPRING_DATA_REDIS_PORT: "6379"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  EUREKA_CLIENT_EUREKASERVER_CONNECTTIMEOUTSECONDS: "60"
  EUREKA_CLIENT_EUREKASERVER_READTIMEOUTSECONDS: "60"
  JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
  # Aggressive Heartbeat to solve the K8s/Eureka Desync problem
  EUREKA_INSTANCE_LEASERENEWALINTERVALINSECONDS: "5"
  EUREKA_INSTANCE_LEASEEXPIRATIONDURATIONINSECONDS: "10"
  EUREKA_SERVER_EVICTIONINTERVALTIMERINMS: "5000"

  # DISCONNECTING EUREKA (Switch to Pure K8s DNS Routing)
  EUREKA_CLIENT_ENABLED: "false"
  
  # Overriding API Gateway lb:// routes with direct K8s DNS
  SPRING_CLOUD_GATEWAY_ROUTES_0_URI: "http://employee-service:8081"
  SPRING_CLOUD_GATEWAY_ROUTES_1_URI: "http://address-service:8082"
  SPRING_CLOUD_GATEWAY_ROUTES_2_URI: "http://auth-service:8083"
