apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
  namespace: ems-prod
spec:
  serviceName: "mysql-server"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: mysql:8.0
        envFrom:
        - secretRef:
            name: ems-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: ems-prod
spec:
  selector:
    app: mysql-server
  ports:
    - port: 3306
      targetPort: 3306
