apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
  namespace: ems-prod
spec:
  serviceName: "redis-server"
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-server
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: ems-prod
spec:
  selector:
    app: redis-server
  ports:
    - port: 6379
      targetPort: 6379
