# Port configuration for the API Gateway server to listen on
server:
  port: 9090

spring:
  # The name of this application when it registers with Eureka Service Registry
  application:
    name: ApiGateway
  cloud:
    gateway:
      # Defining the routing logic for incoming requests
      routes:
        # Route for Employee Service
        - id: employee_route
          uri: lb://EMPLOYEE
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<segment>.*), /$\{segment}
            
        # Route for Address Service
        - id: address_route
          uri: lb://ADDRESS
          predicates:
            - Path=/address/**
          filters:
            - RewritePath=/address/(?<segment>.*), /$\{segment}
            
        # Route for Auth Service
        - id: auth_route
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

# Swagger UI Aggregation Configuration
springdoc:
  swagger-ui:
    urls:
      - name: Employee Service
        url: /employee/v3/api-docs
      - name: Address Service
        url: /address/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs

# Configuration for Eureka Client (so Gateway can find other microservices)
eureka:
  client:
    serviceUrl:
      # The URL where Eureka Server is running
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Use the IP address for registration instead of the hostname
    preferIpAddress: true
