server.port=8084

# GitHub OAuth2 Configuration (We need to fill these in!)
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=

# H2 In-Memory Database Configuration for JIT Provisioning
spring.datasource.url=jdbc:h2:mem:ssodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
